function fr_nations_amen_client_mvp_views_hardcoded_DownloadViewImpl_$setWidgetAsExample__Lfr_nations_amen_client_mvp_views_hardcoded_DownloadViewImpl_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static, widget){
  com_google_gwt_user_client_ui_Panel_$clear__Lcom_google_gwt_user_client_ui_Panel_2V(this$static.fr_nations_amen_client_mvp_views_hardcoded_DownloadViewImpl_container);
  com_google_gwt_user_client_ui_SimplePanel_$add__Lcom_google_gwt_user_client_ui_SimplePanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.fr_nations_amen_client_mvp_views_hardcoded_DownloadViewImpl_container, widget);
}

com_google_gwt_lang_SeedUtil_defineSeed__IILcom_google_gwt_core_client_JavaScriptObject_2Lcom_google_gwt_core_client_JavaScriptObject_2(1097, 1, makeCastMap([Q$com_google_gwt_core_client_RunAsyncCallback]));
_.onSuccess__V = function fr_nations_amen_client_mvp_views_hardcoded_DownloadViewImpl$1_onSuccess__V(){
  fr_nations_amen_client_mvp_views_hardcoded_DownloadViewImpl_$setWidgetAsExample__Lfr_nations_amen_client_mvp_views_hardcoded_DownloadViewImpl_2Lcom_google_gwt_user_client_ui_Widget_2V(this.fr_nations_amen_client_mvp_views_hardcoded_DownloadViewImpl$1_this$0, this.fr_nations_amen_client_mvp_views_hardcoded_DownloadViewImpl$1_val$myDownloadPanel);
}
;
$entry(com_google_gwt_core_client_impl_AsyncFragmentLoader_onLoad__IV)(2);
