function fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl_$setWidgetAsExample__Lfr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static, widget){
  this$static.fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl_container.clear__V();
  com_google_gwt_user_client_ui_SimplePanel_$add__Lcom_google_gwt_user_client_ui_SimplePanel_2Lcom_google_gwt_user_client_ui_Widget_2V(this$static.fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl_container, widget);
}

com_google_gwt_lang_SeedUtil_defineSeed__IILcom_google_gwt_core_client_JavaScriptObject_2Lcom_google_gwt_core_client_JavaScriptObject_2(1108, 1, makeCastMap([Q$com_google_gwt_core_client_RunAsyncCallback]));
_.onSuccess__V = function fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl$1_onSuccess__V(){
  this.fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl$1_this$0.fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl_cellListTemoignagesrManager = this.fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl$1_val$scroll;
  fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl_$setWidgetAsExample__Lfr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl_2Lcom_google_gwt_user_client_ui_Widget_2V(this.fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl$1_this$0, this.fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl$1_this$0.fr_nations_amen_client_mvp_views_hardcoded_TemoignagesViewImpl_cellListTemoignagesrManager);
}
;
$entry(com_google_gwt_core_client_impl_AsyncFragmentLoader_onLoad__IV)(3);
